apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulsar-cluster
  namespace: pulsar2
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: pulsar2
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.streamnative.io'
    targetRevision: 1.3.0
    chart: pulsar
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true

